### ISSUE TITLE
Deploy step seems to be running for all jobs instead just the osx one

### ISSUE THREAD

**Issue by 9prady9** [9prady9/MeshIO#43]
https://travis-ci.org/github/9prady9/MeshIO/jobs/663364634?utm_medium=notification&utm_source=github_status

https://travis-ci.org/github/9prady9/MeshIO/jobs/663364635?utm_medium=notification&utm_source=github_status

https://travis-ci.org/github/9prady9/MeshIO/jobs/663364636?utm_medium=notification&utm_source=github_status

**Comment by acrlakshman** [comment]
Yes, realized that while testing on my fork. Thought I will come back later on that.

**Comment by 9prady9** [comment]
Well, one of the jobs are randomly failing since all are trying to create a commit on the gh-pages branch.

Also, I noticed that some earlier commits are gone from that gh-pages branch. Can you please look into it so that we are updating documentation like other branches on git and not override commits.

**Comment by 9prady9** [comment]
Bummer, now it is not running at all. The condition needs to be checked on the fork before we merge again.

**Comment by acrlakshman** [comment]
Sure, I will take a look at this.
